/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IniciativaRouteImport } from './routes/iniciativa'
import { Route as DonarIndexRouteImport } from './routes/donar/index'
import { Route as DonarSlugRouteImport } from './routes/donar/$slug'
import { Route as VoluntariosIndexRouteImport } from './routes/voluntarios/index'
import { Route as VoluntariosPerfilRouteImport } from './routes/voluntarios/perfil'
import { Route as VoluntariosUnirseRouteImport } from './routes/voluntarios/unirse'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedDashboardCampanasRouteImport } from './routes/_authenticated.dashboard.campanas'
import { Route as AuthenticatedDashboardContactosRouteImport } from './routes/_authenticated.dashboard.contactos'
import { Route as AuthenticatedDashboardDonacionesRouteImport } from './routes/_authenticated.dashboard.donaciones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciativaRoute = IniciativaRouteImport.update({
  id: '/iniciativa',
  path: '/iniciativa',
  getParentRoute: () => rootRouteImport,
} as any)
const DonarIndexRoute = DonarIndexRouteImport.update({
  id: '/donar/',
  path: '/donar/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonarSlugRoute = DonarSlugRouteImport.update({
  id: '/donar/$slug',
  path: '/donar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VoluntariosIndexRoute = VoluntariosIndexRouteImport.update({
  id: '/voluntarios/',
  path: '/voluntarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoluntariosPerfilRoute = VoluntariosPerfilRouteImport.update({
  id: '/voluntarios/perfil',
  path: '/voluntarios/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const VoluntariosUnirseRoute = VoluntariosUnirseRouteImport.update({
  id: '/voluntarios/unirse',
  path: '/voluntarios/unirse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardCampanasRoute =
  AuthenticatedDashboardCampanasRouteImport.update({
    id: '/dashboard/campanas',
    path: '/dashboard/campanas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardContactosRoute =
  AuthenticatedDashboardContactosRouteImport.update({
    id: '/dashboard/contactos',
    path: '/dashboard/contactos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardDonacionesRoute =
  AuthenticatedDashboardDonacionesRouteImport.update({
    id: '/dashboard/donaciones',
    path: '/dashboard/donaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/iniciativa': typeof IniciativaRoute
  '/donar/$slug': typeof DonarSlugRoute
  '/voluntarios/perfil': typeof VoluntariosPerfilRoute
  '/voluntarios/unirse': typeof VoluntariosUnirseRoute
  '/donar/': typeof DonarIndexRoute
  '/voluntarios/': typeof VoluntariosIndexRoute
  '/dashboard/campanas': typeof AuthenticatedDashboardCampanasRoute
  '/dashboard/contactos': typeof AuthenticatedDashboardContactosRoute
  '/dashboard/donaciones': typeof AuthenticatedDashboardDonacionesRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/iniciativa': typeof IniciativaRoute
  '/donar/$slug': typeof DonarSlugRoute
  '/voluntarios/perfil': typeof VoluntariosPerfilRoute
  '/voluntarios/unirse': typeof VoluntariosUnirseRoute
  '/donar': typeof DonarIndexRoute
  '/voluntarios': typeof VoluntariosIndexRoute
  '/dashboard/campanas': typeof AuthenticatedDashboardCampanasRoute
  '/dashboard/contactos': typeof AuthenticatedDashboardContactosRoute
  '/dashboard/donaciones': typeof AuthenticatedDashboardDonacionesRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/iniciativa': typeof IniciativaRoute
  '/donar/$slug': typeof DonarSlugRoute
  '/voluntarios/perfil': typeof VoluntariosPerfilRoute
  '/voluntarios/unirse': typeof VoluntariosUnirseRoute
  '/donar/': typeof DonarIndexRoute
  '/voluntarios/': typeof VoluntariosIndexRoute
  '/_authenticated/dashboard/campanas': typeof AuthenticatedDashboardCampanasRoute
  '/_authenticated/dashboard/contactos': typeof AuthenticatedDashboardContactosRoute
  '/_authenticated/dashboard/donaciones': typeof AuthenticatedDashboardDonacionesRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/iniciativa'
    | '/donar/$slug'
    | '/voluntarios/perfil'
    | '/voluntarios/unirse'
    | '/donar/'
    | '/voluntarios/'
    | '/dashboard/campanas'
    | '/dashboard/contactos'
    | '/dashboard/donaciones'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/iniciativa'
    | '/donar/$slug'
    | '/voluntarios/perfil'
    | '/voluntarios/unirse'
    | '/donar'
    | '/voluntarios'
    | '/dashboard/campanas'
    | '/dashboard/contactos'
    | '/dashboard/donaciones'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/iniciativa'
    | '/donar/$slug'
    | '/voluntarios/perfil'
    | '/voluntarios/unirse'
    | '/donar/'
    | '/voluntarios/'
    | '/_authenticated/dashboard/campanas'
    | '/_authenticated/dashboard/contactos'
    | '/_authenticated/dashboard/donaciones'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  IniciativaRoute: typeof IniciativaRoute
  DonarSlugRoute: typeof DonarSlugRoute
  VoluntariosPerfilRoute: typeof VoluntariosPerfilRoute
  VoluntariosUnirseRoute: typeof VoluntariosUnirseRoute
  DonarIndexRoute: typeof DonarIndexRoute
  VoluntariosIndexRoute: typeof VoluntariosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciativa': {
      id: '/iniciativa'
      path: '/iniciativa'
      fullPath: '/iniciativa'
      preLoaderRoute: typeof IniciativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donar/': {
      id: '/donar/'
      path: '/donar'
      fullPath: '/donar/'
      preLoaderRoute: typeof DonarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donar/$slug': {
      id: '/donar/$slug'
      path: '/donar/$slug'
      fullPath: '/donar/$slug'
      preLoaderRoute: typeof DonarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voluntarios/': {
      id: '/voluntarios/'
      path: '/voluntarios'
      fullPath: '/voluntarios/'
      preLoaderRoute: typeof VoluntariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voluntarios/perfil': {
      id: '/voluntarios/perfil'
      path: '/voluntarios/perfil'
      fullPath: '/voluntarios/perfil'
      preLoaderRoute: typeof VoluntariosPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voluntarios/unirse': {
      id: '/voluntarios/unirse'
      path: '/voluntarios/unirse'
      fullPath: '/voluntarios/unirse'
      preLoaderRoute: typeof VoluntariosUnirseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/campanas': {
      id: '/_authenticated/dashboard/campanas'
      path: '/dashboard/campanas'
      fullPath: '/dashboard/campanas'
      preLoaderRoute: typeof AuthenticatedDashboardCampanasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/contactos': {
      id: '/_authenticated/dashboard/contactos'
      path: '/dashboard/contactos'
      fullPath: '/dashboard/contactos'
      preLoaderRoute: typeof AuthenticatedDashboardContactosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/donaciones': {
      id: '/_authenticated/dashboard/donaciones'
      path: '/dashboard/donaciones'
      fullPath: '/dashboard/donaciones'
      preLoaderRoute: typeof AuthenticatedDashboardDonacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardCampanasRoute: typeof AuthenticatedDashboardCampanasRoute
  AuthenticatedDashboardContactosRoute: typeof AuthenticatedDashboardContactosRoute
  AuthenticatedDashboardDonacionesRoute: typeof AuthenticatedDashboardDonacionesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardCampanasRoute: AuthenticatedDashboardCampanasRoute,
  AuthenticatedDashboardContactosRoute: AuthenticatedDashboardContactosRoute,
  AuthenticatedDashboardDonacionesRoute: AuthenticatedDashboardDonacionesRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  IniciativaRoute: IniciativaRoute,
  DonarSlugRoute: DonarSlugRoute,
  VoluntariosPerfilRoute: VoluntariosPerfilRoute,
  VoluntariosUnirseRoute: VoluntariosUnirseRoute,
  DonarIndexRoute: DonarIndexRoute,
  VoluntariosIndexRoute: VoluntariosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
